### ISSUE TITLE
Backlight will remain turned on

### ISSUE THREAD

**Issue by Quallenauge** [Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#7] opened 2018-02-13 07:30 UTC
The issue occurs on the following conditions:
- Ambient Display is activated
- the device is connected to USB
- receive a notification

**Comment by Quallenauge** [comment] 2018-02-13 07:57
Vlad (vladimiroltean) does some research and pointed out:

> I came to the conclusion it's not the HAL (liblights). When the issue happens, the value of zero is correctly being written all the way down to /sys/class/leds/lcd-backlight/brightness. Despite the driver thinking the brightness is 0, the backlight is on. The problem is definitely inside drivers/video/backlight/lp855x_bl.c (or around that place)
> if I force the backlight to go off again, it turns off indeed:
> YTX703L:/ # cat /sys/class/leds/lcd-backlight/brightness
> 0
> YTX703L:/ # echo 0 > /sys/class/leds/lcd-backlight/brightness

**Comment by vladimiroltean** [comment] 2018-02-15 02:40
Summary of the research done:

1. The YT-X703 uses a Texas Instruments LP8557 backlight controller, defined in the DTS file `arch/arm/boot/dts/qcom/msm8976-mtp.dtsi` in the node `backlight@2c`, connected to the node `&i2c_2`.
2. The userspace HAL (`/system/lib64/hw/lights.msm8952.so`, source under `device/lenovo/msm8976-common/liblight/lights.c`) drives the backlight through the sysfs node `/sys/class/leds/lcd-backlight/brightness`. On a side note, the other LED present on this board, the while power LED, is also controlled by liblights through `/sys/class/leds/green/brightness`.
3. The kernel driver's location is in `drivers/video/backlight/lp855x_bl.c`. Normally (in [CAF](https://github.com/vladimiroltean/android_kernel_lenovo_msm8976/blob/LA.BR.1.3.6.c2-03420-8976.0/drivers/video/backlight/lp855x_bl.c) and [upstream](https://github.com/torvalds/linux/blob/master/drivers/video/backlight/lp855x_bl.c)), this driver registers to the *backlight subsystem* and thus exposes its interface through `/sys/class/backlight/lcd-bl`.
4. As stated in bullet 2, the liblights HAL is constructed as to access the backlight driver through the *LEDs subsystem* (`/sys/class/leds/lcd-backlight`). My limited understanding, so far, of the LED subsystem, tells me that this is a bit of a stretch, as an LED driver would normally be able to get/set the brightness only as a `enum led_brightness` which takes values of `LED_OFF=0, LED_HALF=127, LED_FULL=255`. Nonetheless, intermediary values can be set to the brightness, that is how it works when it works, and thus, this is not *the* problem.
5. The problem is that our Lenovo-customized driver registers with *both* the LED and the backlight subsystems. At least according to this comment: `struct led_classdev»    cdev;//yxw add for test`, the leds interface was only intended for testing purposes, and not to be left in the final release. Oh well. The callbacks registered with the backlight subsystem sit mostly idle, because liblights controls it over the leds sysfs node. That much is clear. But the issue arises exactly when the backlight subsystem decides not to be idle anymore, and the `struct backlight_ops lp855x_bl_ops.update_status = lp855x_bl_update_status` gets called.
6. The culprit lies in the aforementioned callback from the backlight subsystem (`lp855x_bl_update_status`), where somebody decided to `lp855x_write_byte(lp, lp->cfg->reg_brightness, val);` instead of properly calling the other function (`lp855x_lcd_bl_set`) which does the bookkeeping from Android's perspective. No wonder reading `/sys/class/leds/lcd-backlight/brightness` was returning 0, since it was a value cached by the kernel (the driver doesn't register any getter callback with the leds subsystem).
7. The following check was probably designed to prevent the situation where subsystem B overrides the brightness set by subsystem A: `if (bl->props.state & BL_CORE_SUSPENDED) bl->props.brightness = 0;`. However, either a race condition, or perhaps that condition not being satisfied at all, is causing the issue we have at hand here.

Given the above explanation, we can either

- Remove the driver's registration with the backlight subsystem. **Advantages:** (1) problem solved quite quickly (2) no modification is needed at the HAL level (liblights) **Disadvantages:** our driver diverges quite a lot from CAF/upstream and will probably need babysitting each time we do a rebase.
- Remove the driver's registration with the LED subsystem, and make the backlight subsystem work properly. **Advantages:** (1) it's The Right Thing (TM) (2) also problem solved **Disadvantages:** (1) liblights will need a very small change (2) I don't even want to know why Lenovo gave up on doing this themselves.

-Vladimir

**Comment by Gabriel85** [comment] 2018-02-15 06:21
Thanks for your work! I'm currently revising/removing all the kernel modifications from Lenovo. If you want to rewrite the kernel driver, feel free to do so! Nearly all of the changes are for that CABL bullshit, which I wanted to remove, anyways. The driver has already been heavily modified by Lenovo, so it wouldn't make any difference... Also frequent upstream updates for this driver are not to be expected. Btw, have you tried to remove all Lenovo modification, yet?

**Comment by vladimiroltean** [comment] 2018-02-15 12:15
The changes to the lp85xx backlight driver are intertwined with more changes to `drivers/video/msm/mdss/mdss_fb.c` that I don't fully understand yet.
I did try to revert Lenovo's patch on the backlight subsystem and I wasn't able to control it anymore. At the time I did not realize that I should have tried to poke the sysfs node `/sys/class/backlight/lcd-bl/brightness` instead of the leds entry. What the Lenovo guys seem to have done is move around the leds sysfs entry created by `mdss_fb.c` from `lcd-backlight` to `yxw-lcd-backlight`. That is to make room for the leds entry of lp85xx,
I guess the next thing to try out is to:

- partially revert `lenovo: drivers/video: changes over CAF tag LA.BR.1.3.4-06610-8976.0`
- see what sysfs node it registers with the backlight subsystem
- poke it around with echo/cat to see if it works
- recompile the liblights hal to use the new sysfs node.

**Comment by vladimiroltean** [comment] 2018-02-15 16:38
UPDATE: Even with the current patch in place, I have seen the backlight remain on at least once, under unknown circumstances (NOT connected to USB, but while it was in its carrying case). Will undergo further investigation.

**Comment by Quallenauge** [comment] 2018-02-15 19:16
Hm. this remembers me to my own build of twrp. I used one of your (vlad) kernel als base and added the ramoops memory section. When TWRP switches to power save mode, the display is blank - but the backlight is on. Is this the same behavior?!

**Comment by vladimiroltean** [comment] 2018-02-16 00:31
The official TWRP build uses a pre-built stock kernel, as far as I am aware. Your issue might as well be related.
However, the mechanism of setting the backlight in TWRP is a bit different (searching for `TW_BRIGHTNESS_PATH` will tell you all there is to know).
I have experimented with reverting `lenovo: drivers/video: changes over CAF tag LA.BR.1.3.4-06610-8976.0` and pointing liblights to the new sysfs node, and yes, it works nicely so far :)
The patches will be available once they are properly cleaned up.

**Comment by Gabriel85** [comment] 2018-02-16 00:35
Thanks for the tip! With that I think I now more than 2/3 of the Lenovo Kernel modifications can be removed.. Only a few lines are left now.. :D

**Comment by vladimiroltean** [comment] 2018-02-16 00:49
One other thing still remains a mystery to me though.
Why, if even AOSP seems to prefer `/sys/class/leds/lcd-backlight/brightness` (as seen in [init.rc](https://github.com/LineageOS/android_system_core/blob/lineage-15.1/rootdir/init.rc#L624)), did the original CAF driver for lp855x not register with the preferred subsystem, and instead Lenovo had to dabble at that? Are there any disadvantages to the backlight subsystem vs leds?

**Comment by Gabriel85** [comment] 2018-02-16 00:53
The init.rc are not from AOSP or Lenovo! They were written by Samsung and taken from the Kenzo.. They do other stupid stuff, too! We should replace them with the original ones from Lenovo, or with some other more neutral ones. I'm telling that for months now, but Christian always refused to replace them with the proper ones.

**Comment by vladimiroltean** [comment] 2018-02-16 00:55
Do you even read?

**Comment by Gabriel85** [comment] 2018-02-16 01:01
Sorry, I'm using my Email-client and didn't see the link!
Than let's take these inits and modify them, so that they work with our ROM?
I don't know why Lenovo changed that, it crashes the kernel, even then stock one. I guess they changed it for debug reasons, and than forgot to take it out again. Also they changed the code to implement CABL.

**Comment by vladimiroltean** [comment] 2018-02-16 01:23
I bring the following branches to your scrutiny:

- https://github.com/vladimiroltean/android_device_lenovo_msm8976_common/commits/backlight-the-right-way
- https://github.com/vladimiroltean/android_kernel_lenovo_msm8976/commits/backlight-the-right-way
- https://github.com/vladimiroltean/android_kernel_lenovo_msm8976/commits/backlight-hackish-solution

Please test them to death.

**Comment by vladimiroltean** [comment] 2018-02-19 21:39
Tested for long enough. This is fixed with no side effects. Merged into my [cm-14.1](https://github.com/vladimiroltean/android_device_lenovo_msm8976_common/commits/cm-14.1) branch (also in line with [Christian's](https://github.com/ChristianCiach/android_device_lenovo_msm8976_common/commits/cm-14.1)). Closing.

**Closed as completed by vladimiroltean** 2018-02-19 21:39 UTC
Labels: bug

**Comment by Quallenauge** [comment] 2018-02-20 06:16
Is the kernel part obsolete now? I see only the liblights implementation changes at the device tree, not in the kernel.

**Comment by vladimiroltean** [comment] 2018-02-20 15:32
The kernel driver was reverted to the stock CAF version via these patches:
* https://github.com/vladimiroltean/android_kernel_lenovo_msm8976/commit/7145d7f9a1826e05fa53fbe626fa9fa8274934bd
* https://github.com/vladimiroltean/android_kernel_lenovo_msm8976/commit/c8aea4f7e4d1b160ea6e475d3cfaed831740e0f3
* https://github.com/vladimiroltean/android_kernel_lenovo_msm8976/commit/04a21519bd1322dd8ec3b30a375730695bcc707a
* https://github.com/vladimiroltean/android_kernel_lenovo_msm8976/commit/a9f3c44af1f5ab2744e600e4c38ad2e94d455cee

**Comment by Quallenauge** [comment] 2018-02-20 19:53
Thanks for clarification! :+1:
